export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const SUCCESSFULLY_LOGIN = 'SUCCESSFULLY_LOGIN';
export const SUCCESSFULLY_REGISTERED_USER = 'SUCCESSFULLY_REGISTERED_USER';
export const ERROR_REGISTERING_USER = 'ERROR_REGISTERING_USER';
export const ERROR_AUTH_USER = 'ERROR_AUTH_USER';
export const CLOSE_SESSION = 'CLOSE_SESSION';

export const CLEAN_ALERT = 'CLEAN_ALERT';
export const SHOW_ALERT = 'SHOW_ALERT';


export const SUCCESSFULLY_UPLOAD_FILE = 'SUCCESSFULLY_UPLOAD_FILE';
export const ERROR_UPLOAD_FILE = 'ERROR_UPLOAD_FILE';

export const SUCCESSFULLY_CREATE_LINK = 'SUCCESSFULLY_CREATE_LINK';
export const ERROR_CREATE_LINK = 'ERROR_CREATE_LINK';

export const UPLOAD_FILE = 'UPLOAD_FILE';

export const CLEAN_STATE = 'CLEAN_STATE';

export const ADD_PASSWORD = 'ADD_PASSWORD';

export const ADD_DOWNLOADS = 'ADD_DOWNLOADS';