export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const SUCCESSFULLY_REGISTERED_USER = 'SUCCESSFULLY_REGISTERED_USER';
export const ERROR_REGISTERING_USER = 'ERROR_REGISTERING_USER';
export const CLEAN_ALERT = 'CLEAN_ALERT';